services:
 sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest 
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
    ports: 
        - "127.0.0.1:1433:1433"
    volumes:
        - sqlserver_data:/var/opt/mssql
    healthcheck:
        test: ["CMD-SHELL", "pgrep sqlservr || exit 1"]
        interval: 10s
        timeout: 5s
        retries: 10
 api:
    build:
      context: .
      dockerfile: API/Dockerfile
    container_name: dodlj-api
    environment:
     ASPNETCORE_ENVIRONMENT: Production
     ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=${DB_NAME};User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;"
     DocumentationEditApiKey: "${DOCUMENTATION_EDIT_API_KEY}"
    depends_on:
      sqlserver:
        condition: service_healthy
    ports:
      - "5000:8080"
 blazor:
    build:
       context: .
       dockerfile: Blazor/Dockerfile
    container_name: dodlj-blazor
    depends_on:
      - api
    ports:
     - "8080:80"
    
volumes:
  sqlserver_data:
